# Generated by Django 4.1.1 on 2022-10-06 18:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_type', models.CharField(blank=True, choices=[('Monday Special', 'Monday Special'), ('Lucky Tuesday', 'Lucky Tuesday'), ('Mid Week', 'Mid Week'), ('Fortune Thursday', 'Fortune Thursday'), ('Friday Bonaza', 'Friday Bonaza'), ('National Weekly Lotto', 'National Weekly Lotto'), ('Sunday Aseda', 'Sunday Aseda')], max_length=100, null=True)),
                ('date_select', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AddWinDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_type', models.CharField(blank=True, choices=[('Monday Special', 'Monday Special'), ('Lucky Tuesday', 'Lucky Tuesday'), ('Mid Week', 'Mid Week'), ('Fortune Thursday', 'Fortune Thursday'), ('Friday Bonaza', 'Friday Bonaza'), ('National Weekly Lotto', 'National Weekly Lotto'), ('Sunday Aseda', 'Sunday Aseda')], max_length=100, null=True)),
                ('date_select', models.CharField(default='', max_length=50)),
                ('first_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[pages.models.less_than])),
                ('second_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[pages.models.less_than])),
                ('third_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[pages.models.less_than])),
                ('fourth_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[pages.models.less_than])),
                ('fifth_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[pages.models.less_than])),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('image', models.ImageField(default='mediafiles/avatar.png', max_length=30, null=True, upload_to='mediafiles/')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('author', models.CharField(default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('image', models.ImageField(default='mediafiles/avatar.png', max_length=30, null=True, upload_to='mediafiles/')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('author', models.CharField(default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('body', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.blog')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='AllDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_draw', models.CharField(blank=True, default='', max_length=50)),
                ('mobile_only', models.CharField(blank=True, default='', max_length=50)),
                ('total_price', models.CharField(blank=True, default='', max_length=50)),
                ('total_won', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('add_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.adddraw')),
                ('win_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.addwindraw')),
            ],
        ),
    ]
