from django.urls import path

from .views import (
    pages_authentication_login_view,
    pages_authentication_register_view,
    pages_authentication_recoverpw_view,
    pages_authentication_lockscreen_view,
    pages_authentication_logout_view,
    pages_authentication_confirm_mail_view,
    pages_authentication_email_verification_view,
    pages_authentication_two_step_verification_view,
    pages_starter_page_view,
    pages_maintenance_view,
    pages_comingsoon_view,
    pages_timeline_view,
    pages_faqs_view,
    pages_pricing_view,
    pages_error_404_view,
    pages_error_500_view,
    pages_horizontal_layout_view,
    pages_blogs_view,
    pages_create_blog_view,
    pages_add_draw_view,
    pages_all_draws_view,
    pages_all_draw_form_view,
    pages_all_draw_edit_view ,
    pages_all_draw_delete_view,
    pages_all_users_view,
    pages_all_forecasters_view,
    pages_merchants_view,
    pages_number_verification_view,
    pages_add_user_view,
    pages_users_view,
    pages_add_merchant_stake_view,
    pages_all_merchant_stake_view,
    pages_all_user_stakes_view,
    pages_delete_blog_view,
    pages_create_testimonial_view,
    pages_delete_testimonial_view,
    pages_view_testimonial_view,
    pages_testimonials_view,
    pages_view_blog_view,
    pages_add_win_draw_view,
    pages_banker_stats_view,
    pages_banker_view,
    pages_bankers_view,
    pages_deposit_credit_view,
    pages_add_recent_stakes_view,
    pages_add_recent_wins_view,
    pages_local_withdraw_view,
    pages_bank_withdraw_view,
    pages_commissions_view,
    pages_latest_transactions_view,
    pages_win_audits_view,
    pages_win_audit_fail_view,
    pages_all_subscriptions_view,
    pages_account_summary_view,
    pages_account_services_view,
    
)

app_name = "pages"

urlpatterns = [
    # Authentication
    path(
        "authentication/login",
        view=pages_authentication_login_view,
        name="pages.authentication.login",
    ),
    path(
        "authentication/register",
        view=pages_authentication_register_view,
        name="pages.authentication.register",
    ),
    path(
        "authentication/recoverpw",
        view=pages_authentication_recoverpw_view,
        name="pages.authentication.recoverpw",
    ),
    path(
        "authentication/lock-screen",
        view=pages_authentication_lockscreen_view,
        name="pages.authentication.lockscreen",
    ),
    path(
        "authentication/logout",
        view=pages_authentication_logout_view,
        name="pages.authentication.logout",
    ),
    path(
        "authentication/confirm_mail",
        view=pages_authentication_confirm_mail_view,
        name="pages.authentication.confirm_mail",
    ),
    path(
        "forms/email_verification",
        view=pages_authentication_email_verification_view,
        name="pages.authentication.email_verification",
    ),
    path(
        "forms/two_step_verification",
        view=pages_authentication_two_step_verification_view,
        name="pages.authentication.two_step_verification",
    ),
    # pages
    path(
        "starter-page",
        view=pages_starter_page_view,
        name="pages.starter_page",
    ),
    path(
        "maintenance",
        view=pages_maintenance_view,
        name="pages.maintenance",
    ),
    path(
        "comingsoon",
        view=pages_comingsoon_view,
        name="pages.comingsoon",
    ),
    path(
        "timeline",
        view=pages_timeline_view,
        name="pages.timeline",
    ),
    path(
        "faqs",
        view=pages_faqs_view,
        name="pages.faqs",
    ),
    path(
        "pricing",
        view=pages_pricing_view,
        name="pages.pricing",
    ),
    path(
        "error-404",
        view=pages_error_404_view,
        name="pages.error_404",
    ),
    path(
        "error-500",
        view=pages_error_500_view,
        name="pages.error_500",
    ),
    
    #  Karlo Added Pages
    #Blogs
    path(
        "blogs",
        view=pages_blogs_view,
        name="pages.blogs",
    ),
    path(
        "create-blog",
        view=pages_create_blog_view,
        name="pages.create_blog",
    ),
    path(
        "blogs<int:pk>/delete-blog",
        view=pages_delete_blog_view,
        name="pages.delete_blog",
    ),
    path(
        "blogs<int:pk>/view-blog",
        view=pages_view_blog_view,
        name="pages.view_blog",
    ),
    
    #Testimonials
    path(
        "testimonials",
        view=pages_testimonials_view,
        name="pages.testimonials",
    ),
    path(
        "create-testimonial",
        view=pages_create_testimonial_view,
        name="pages.create_testimonial",
    ),
    path(
        "testimonials<int:pk>delete-testimonial",
        view=pages_delete_testimonial_view,
        name="pages.delete_testimonial",
    ),
    path(
        "testimonials<int:pk>view-testimonial",
        view=pages_view_testimonial_view,
        name="pages.view_testimonial",
    ),
    
    #Add Draw 
    path(
        "add-draw",
        view=pages_add_draw_view,
        name="pages.add_draw",
    ),
    path(
        "all-draws",
        view=pages_all_draws_view,
        name="pages.all_draws",
    ),
    path(
        "all-draws-form",
        view=pages_all_draw_form_view,
        name="pages.all_draws-form",
    ),
    path(
        "all-draws<int:pk>edit",
        view=pages_all_draw_edit_view ,
        name="pages.all_draws-edit",
    ),
     path(
        "all-draws<int:pk>delete",
        view=pages_all_draw_delete_view,
        name="pages.all_draws-delete",
    ),
    path(
        "add-win-draw",
        view=pages_add_win_draw_view,
        name="pages.add_win_draw",
    ),
    
    #Account
    path(
        "deposit-credit",
        view=pages_deposit_credit_view,
        name="pages.deposit_credit",
    ),
    path(
        "local-withdrawals",
        view=pages_local_withdraw_view,
        name="pages.local_withdrawals",
    ),
    path(
        "bank-withdrawals",
        view=pages_bank_withdraw_view,
        name="pages.bank_withdrawals",
    ),
    path(
        "commissions",
        view=pages_commissions_view,
        name="pages.commissions",
    ),
    path(
        "latest-transactions",
        view=pages_latest_transactions_view,
        name="pages.latest_transactions",
    ),
    path(
        "win-audits",
        view=pages_win_audits_view,
        name="pages.win_audits",
    ),
    path(
        "win-audit-fail",
        view=pages_win_audit_fail_view,
        name="pages.win_audit_fail",
    ),
    path(
        "all-subscriptions",
        view=pages_all_subscriptions_view,
        name="pages.all_subscriptions",
    ),
    path(
        "account-summary",
        view=pages_account_summary_view,
        name="pages.account_summary",
    ),
    path(
        "account-services",
        view=pages_account_services_view,
        name="pages.account_services",
    ),
     
    #Users 
    path(
        "all-users",
        view=pages_all_users_view,
        name="pages.all_users",
    ),
    path(
        "all-forecasters",
        view=pages_all_forecasters_view,
        name="pages.all_forecasters",
    ),
    path(
        "merchants",
        view=pages_merchants_view,
        name="pages.merchants",
    ),
    
    #Bankers 
    path(
        "bankers",
        view=pages_bankers_view,
        name="pages.bankers",
    ),
    path(
        "add-banker",
        view=pages_banker_view,
        name="pages.add_banker",
    ),
    path(
        "banker-stats",
        view=pages_banker_stats_view,
        name="pages.banker_stats",
    ),
    
    #Add-ons
    path(
        "add-recent-stakes",
        view=pages_add_recent_stakes_view,
        name="pages.add_recent_stakes",
    ),
    path(
        "add-recent-wins",
        view=pages_add_recent_wins_view,
        name="pages.add_recent_wins",
    ),
    
    #Number Verification 
    path(
        "number-verification",
        view=pages_number_verification_view,
        name="pages.number_verification",
    ),
    
    #Users
    path(
        "users",
        view=pages_users_view,
        name="pages.user_view",
    ),
    path(
        "add-user",
        view=pages_add_user_view,
        name="pages.add_user",
    ),
    
    #All Stakes
    path(
        "all-user-stakes",
        view=pages_all_user_stakes_view,
        name="pages.all_user_stakes",
    ),
    path(
        "add-merchant-stake",
        view=pages_add_merchant_stake_view,
        name="pages.add_merchant_stake",
    ),
    path(
        "all-merchant-stakes",
        view=pages_all_merchant_stake_view,
        name="pages.all_merchant_stake",
    ),
    
    #  Layout
    path(
        "layout/horizontal",
        view=pages_horizontal_layout_view,
        name="pages.layout.horizontal",
    ),
]
