# Generated by Django 4.1.1 on 2022-09-27 10:52

from django.db import migrations, models
import django.db.models.deletion
import mainwebsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('mainwebsite', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistroyAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(blank=True, choices=[('Monday Special', 'Monday Special'), ('Lucky Tuesday', 'Lucky Tuesday'), ('Lucky Wednesday', 'Lucky Tuesday'), ('Lucky Thursday', 'Lucky Tuesday'), ('Lucky Friday', 'Lucky Tuesday')], max_length=100, null=True)),
                ('perm_type', models.CharField(blank=True, choices=[('2 Direct ', '2 Direct'), ('3 Direct', '3 Direct'), ('Perm 2', 'Perm 2'), ('Perm 3', 'Perm 3')], max_length=100, null=True)),
                ('first_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('second_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('third_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('fourth_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('fifth_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('price', models.FloatField(blank=True, max_length=100, null=True)),
                ('winning_amount', models.FloatField(blank=True, max_length=100, null=True)),
                ('payment', models.FloatField(blank=True, max_length=100, null=True)),
                ('date_stake', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositHistory',
            fields=[
                ('histroyabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainwebsite.histroyabstract')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('mainwebsite.histroyabstract',),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('histroyabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainwebsite.histroyabstract')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('mainwebsite.histroyabstract',),
        ),
        migrations.CreateModel(
            name='withdrawHistory',
            fields=[
                ('histroyabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainwebsite.histroyabstract')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('mainwebsite.histroyabstract',),
        ),
        migrations.CreateModel(
            name='ForecasterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_type', models.CharField(blank=True, choices=[('Monday Special', 'Monday Special'), ('Lucky Tuesday', 'Lucky Tuesday'), ('Mid Week', 'Mid Week'), ('Fortune Thursday', 'Fortune Thursday'), ('Friday Bonaza', 'Friday Bonaza'), ('National Weekly Lotto', 'National Weekly Lotto'), ('Sunday Aseda', 'Sunday Aseda')], default='', max_length=100, null=True)),
                ('date_select', models.CharField(default='', max_length=50)),
                ('first_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('second_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('third_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('fourth_number', models.PositiveIntegerField(blank=True, default='', null=True, validators=[mainwebsite.models.less_than])),
                ('fifth_number', models.PositiveIntegerField(blank=True, default='', validators=[mainwebsite.models.less_than])),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('win_draw', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.addwindraw')),
            ],
        ),
    ]
